apiVersion: v1
data:
  DB_URL: cG9zdGdyZXM6Ly9zYW1wbGVfYXBwOnNodWJoczEwMEBzYW1wbGUtYXBwLWRiOjU0MzIvc2FtcGxlX2FwcA==
  POSTGRES_PASSWORD: c2h1YmhzMTAw
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-creds
