apiVersion: v1
kind: Pod
metadata:
  name: web-2
  namespace: default
  labels:
    app: web
spec:
  containers:
  - name: sample-app
    image: smudgal2964/sample_app:1.0.8
    ports:
    - containerPort: 3000
    env:
    - name: RAILS_ENV
      value: production
    - name: DATABASE_URL
      value: postgres://sample_app:shubhs100@db:5432/sample_app
