apiVersion: v1
kind: Pod
metadata:
  name: db
  namespace: default
  labels:
    app: db
spec:
  containers:
  - name: postgresql
    image: postgres:16.0-bullseye
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: shubhs100
    - name: POSTGRES_USER
      value: sample_app
    - name: POSTGRES_DB
      value: sample_app
