apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: default
spec:
  containers:
  - name: sample-app
    image: smudgal2964/sample_app:1.0.2
    ports:
    - containerPort: 3000
    env:
    - name: DATABASE_URL
      value: postgres://sample_app:shubhs100@hostname:5432/database
