name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      uses: docker/login-action@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile.production --tag smudgal2964/sample_app:1.0.2
    - name: Push the docker image
      run: docker push smudgal2964/sample_app:1.0.3
    
