name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      uses: docker/login-action@v1
    - name: Build the Docker image
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: docker build --file Dockerfile.production --tag smudgal2964/sample_app:1.0.8 --build-arg RAILS_MASTER_KEY=${{ env.RAILS_MASTER_KEY }} .
    - name: Push the docker image
      run: docker push smudgal2964/sample_app:1.0.8
