name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.production --tag smudgal2964/sample_app:1.0.2
    - name: Push the docker image
      env:
         DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
         # Access the secret using the MY_SECRET_TOKEN environment variable
          echo "My secret token: $MY_SECRET_TOKEN"
    
