name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      uses: docker/login-action@v1
    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
    - name: Build the Docker image
      env:
        RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      run: docker build --file Dockerfile.production --tag smudgal2964/sample_app:${SHORT_SHA} --build-arg RAILS_MASTER_KEY=${{ env.RAILS_MASTER_KEY }} .
    - name: Push the docker image
      run: docker push smudgal2964/sample_app:${SHORT_SHA}
    - name: echo published image tag
      run: echo "Published image tag is: smudgal2964/sample_app:${SHORT_SHA}"
